/* declaring objs that will be used to converting file names */
export const monImgFileMatcher = {
    "Anjanath" : "MHW_Anjanath_Icon.webp",
    "Barroth" : "MHW_Barroth_Icon.webp", 
    "Bazelgeuse" : "MHW_Bazelgeuse_Icon.webp",
    "Seething Bazelgeuse" : "MHWI_Seething_Bazelgeuse_Icon.webp",
    "Behemoth" : "MHW_Behemoth_Icon.webp",
    "Deviljho" : "MHW_Deviljho_Icon.webp",
    "Diablos" : "MHW_Diablos_Icon.webp",
    "Black Diablos" : "MHW_Black_Diablos_Icon.webp",
    "Ancient Leshen" : "MHW_Ancient_Leshen_Icon.webp",
    "Dodogama" : "MHW_Dodogama_Icon.webp",
    "Great Girros" : "MHW_Great_Girros_Icon.webp",
    "Great Jagras" : "MHW_Great_Jagras_Icon.webp",
    "Jyuratodus" : "MHW_Jyuratodus_Icon.webp",
    "Kirin" : "MHW_Kirin_Icon.webp",
    "Kulu-Ya-Ku" : "MHW_Kulu-Ya-Ku_Icon.webp",
    "Kulve Taroth" : "MHW_Kulve_Taroth_Icon.webp",
    "Kushala Daora" : "MHW_Kushala_Daora_Icon.webp",
    'Lavasioth' : "MHW_Lavasioth_Icon.webp",
    'Legiana' : "MHW_Legiana_Icon.webp",
    'Lunastra' : "MHW_Lunastra_Icon.webp",
    'Nergigante' : "MHW_Nergigante_Icon.webp",
    'Odogaron' : "MHW_Odogaron_Icon.webp",
    'Paolumu' : "MHW_Paolumu_Icon.webp",
    'Pukei-Pukei' : "MHW_Pukei-Pukei_Icon.webp",
    'Radobaan' : "MHW_Radobaan_Icon.webp",
    'Rathalos' : "MHW_Rathalos_Icon.webp",
    'Rathian' : "MHW_Rathian_Icon.webp",
    'Pink Rathian' : "MHW_Pink_Rathian_Icon.webp",
    'Teostra' : "MHW_Teostra_Icon.webp", 
    "Savage Deviljho" : "MHWI_Savage_Deviljho_Icon.webp",
    'Tobi-Kadachi' : "MHW_Tobi-Kadachi_Icon.webp",
    'Tzitzi-Ya-Ku' : "MHW_Tzitzi-Ya-Ku_Icon.webp",
    'Uragaan' : "MHW_Uragaan_Icon.webp",
    'Vaal Hazak' : "MHW_Vaal_Hazak_Icon.webp", 
    'Blackveil Vaal Hazak' : "MHWI_Blackveil_Vaal_Hazak_Icon.webp",
    'Xeno\'Jiiva' : "MHW_Xeno%27jiiva_Icon.webp",
    'Zorah Magdaros' : "MHW_Zorah_Magdaros_Icon.webp",
    'Banbaro' : "MHWI_Banbaro_Icon.webp",
    'Belotodus' : "MHWI_Beotodus_Icon.webp",
    'Nargacuga' : "MHWI_Nargacuga_Icon.webp",
    'Velkhana' : "MHWI_Velkhana_Icon.webp",
    'Tigrex' : "MHWI_Tigrex_Icon.webp",
    'Shrieking Legiana' : "MHWI_Shrieking_Legiana_Icon.webp",
    'Barioth' : "MHWI_Barioth_Icon.webp",
    'Glavenus' : "MHWI_Glavenus_Icon.webp",
    'Brachydios' : "MHWI_Brachydios_Icon.webp", 
    'Fulgur Anjanath' : "MHWI_Fulgur_Anjanath_Icon.webp",
    'Ebony Odogaron' : "MHWI_Ebony_Odogaron_Icon.webp",
    'Acidic Glavenus' : "MHWI_Acidic_Glavenus_Icon.webp",
    'Ruiner Nergigante' : "MHWI_Ruiner_Nergigante_Icon.webp",
    'Viper Tobi-Kadachi' : "MHWI_Viper_Tobi-Kadachi_Icon.webp",
    'Coral Pukei-Pukei' : "MHWI_Coral_Pukei-Pukei_Icon.webp",
    'Nightshade Paolumu' : "MHWI_Nightshade_Paolumu_Icon.webp",
    'Namielle' : "MHWI_Namielle_Icon.webp",
    'Yian Garuga' : "MHWI_Yian_Garuga_Icon.webp",
    'Shara Ishvalda' : "MHWI_Shara_Ishvalda_Icon.webp",
    'Scarred Yian Garuga' : "MHWI-Scarred_Yian_Garuga_Icon.webp",
    'Gold Rathian' : "mhwi-gold_rathian_icon.png",
    'Silver Rathalos' : "MHW_Silver_Rathalos.png",
    'Brute Tigrex' : "MHWI_Brute_Tigrex_Icon.webp",
    'Zinogre' : "MHWI_Zinogre_Icon.webp",
    'Rajang' : "MHWI_Rajang_Icon.webp",
    'Fatalis' : "mhwi-fatalis_icon.png",
    'Azure Rathalos' : "MHW-Azure_Rathalos_Icon.webp",
    'Leshen' : "MHW_Leshen_Icon.webp",
    'Stygian Zinogre' : "MHWI-Stygian_Zinogre_Icon.webp",
    'Safi\'jiiva' : "MHWI-Safi%27jiiva_Icon.webp",
    'Raging Brachydios' : "MHWI-Raging_Brachydios_Icon.webp",
    'Furious Rajang' : "MHWI-Furious_Rajang_Icon.webp",
    'Alatreon' : "MHWI-Alatreon_Icon.webp",
    'Frostfang Barioth' : "MHWI-Frostfang_Barioth_Icon.webp",
}

export const weaponIconFileMatcher = {
    'Sword and Shield' : "Sword_and_Shield_Icon_White.webp",
    'Dual Blades' : "Dual_Blades_Icon_White.webp",
    'Long Sword' : "Long_Sword_Icon_White.webp",
    'Great Sword' : "Great_Sword_Icon_White.webp",
    'Lance' : "Lance_Icon_White.webp",
    'Gunlance' : "Gunlance_Icon_White.webp",
    'Hammer' : "Hammer_Icon_White.webp",
    'Hunting Horn' : "Hunting_Horn_Icon_White.webp",
    'Charge Blade' : "Charge_Blade_Icon_White.webp",
    'Switch Axe' : "Switch_Axe_Icon_White.webp",
    'Insect Glaive' : "Insect_Glaive_Icon_White.webp",
    'Light Bowgun' : "Light_Bowgun_Icon_White.webp",
    'Heavy Bowgun' : "Heavy_Bowgun_Icon_White.webp",
    'Bow' : "Bow_Icon_White.webp",
}

export const successStampMatcher = {
    'Yes' : 'quest-clear.png',
    'No' : 'quest-failed.png',
}